### PR TITLE
Add Portuguese holidays

### PR DESCRIPTION
**Pull request by borfast**
Just what the title says :)
This time with the correct branch name ;)

### CODE REVIEW

**Comment by borfast** [comment]
Is there no interest in this? :\

**Comment by Natim** [comment]
There are but @brunobord will look at it after his holidays

**Comment by borfast** [comment]
OK, cool :)
I'll use my fork until then.

**Comment by brunobord** [comment]
it looks great to me. What I don't get is that this branch/PR has not been seen by travis... :(

**Comment by brunobord** [comment]
ah. My bad. it's just that the build status has not been sent back to the commit.

https://travis-ci.org/novapost/workalendar/builds/72556103

It's green, *obrigado, Raúl*

**Comment by borfast** [comment]
Pas de problème, Bruno :)

Thanks for merging it!

**Comment by borfast** [comment]
@brunobord, could you also update the package on Pypi, please?

**Comment by brunobord** [comment]
here it is: https://pypi.python.org/pypi/workalendar/0.4.1

**Comment by borfast** [comment]
Merci beaucoup! :)

**Pull request merged**
